export const moviedata = [{
  movies: [{
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '94',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '59',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '41',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '42',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '99',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '79',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '60',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '94',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '59',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '41',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '42',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '99',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '79',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '60',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '94',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '59',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '41',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '42',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '99',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '79',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '60',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '94',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '59',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '41',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '42',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '99',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '79',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, {
    title: 'Pulp Fiction',
    releaseDate: '19941103',
    genres: ['Crime', 'Drama'],
    urlIMDB: 'http://www.imdb.com',
    urlPoster: '../assets/Pulp-Fiction1.png',
    rating: '8.9',
    metascore: '60',
    runtime: ['2h 34min'],
    plot: 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
  }, ]
}, ];
